/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface AppDownload {}
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface AppUpload {}
}

declare global {


  interface HTMLAppDownloadElement extends Components.AppDownload, HTMLStencilElement {}
  var HTMLAppDownloadElement: {
    prototype: HTMLAppDownloadElement;
    new (): HTMLAppDownloadElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppUploadElement extends Components.AppUpload, HTMLStencilElement {}
  var HTMLAppUploadElement: {
    prototype: HTMLAppUploadElement;
    new (): HTMLAppUploadElement;
  };
  interface HTMLElementTagNameMap {
    'app-download': HTMLAppDownloadElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-upload': HTMLAppUploadElement;
  }
}

declare namespace LocalJSX {
  interface AppDownload extends JSXBase.HTMLAttributes<HTMLAppDownloadElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppUpload extends JSXBase.HTMLAttributes<HTMLAppUploadElement> {}

  interface IntrinsicElements {
    'app-download': AppDownload;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-upload': AppUpload;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


